name: Client Test

on: [push]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Run test on client
      run: |
        cd web
        npm install
        npm run coverage

        
